# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/junaid-16/CodersWeek-ML/blob/master/Day2/Day2.ipynb
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import svm
import pickle

dataframe = pd.read_csv('http://iali.in/datasets/Social_Network_Ads.csv')

"""our target class i.e. 'purchased' contains only two values 0 & 1. As these are two discrete values and also they are categorical we'll need to use classifications model.
we will drop user id and gender column for this task"""

dataframe = dataframe.drop(columns=['User ID','Gender'])
"""visualizing data"""
y = dataframe.iloc[:,2]
x = dataframe.drop(columns='Purchased')

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

model = svm.SVC(kernel='linear')
model.fit(x_train,y_train)

"""using model for prediction and testing accuracy"""

y_pred = model.predict(x_test)
print(accuracy_score(y_test,y_pred))

"""saving model"""
pickle.dump(model, open('model.pkl','wb'))
